// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    int32   `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books,omitempty"`
}

type AuthorInput struct {
	Name string `json:"name"`
}

type Book struct {
	ID       int32   `json:"id"`
	Title    string  `json:"title"`
	AuthorID int32   `json:"authorId"`
	Author   *Author `json:"author"`
}

type BookInput struct {
	Title    string `json:"title"`
	AuthorID int32  `json:"authorId"`
}

type Mutation struct {
}

type Query struct {
}
